### ISSUE TITLE
I'd like to help porting cinder to linux

### ISSUE THREAD

**Issue by microcai** [gaborpapp/Cinder#2]
I am new to cinder, but I'd like to help porting cinder to linux.

linux will soon have wayland, but currently X is dominating.

SDL2 just released, that's great. SDL2 can be an thin layer on top of X and wayland and android.

as audio, I think pulseaudio is the way to go.

But I am completely new to cinder.  that's bad. bad. where to start?

**Comment by gaborpapp** [comment]
There's an official cinder linux port now:
https://github.com/cinder/Cinder/tree/android_linux
